---
# Event stream-specific configuration options:
event-stream:
  # Configuration of the Tendermint API:
  websocket:
    uri: ${EVENT_STREAM_WEBSOCKET_URI}
    throttle-duration-ms: 0
  rpc:
    uri: ${EVENT_STREAM_RPC_URI}
  batch:
    # Controls the maximum number of blocks that will be bundled into a batch for processing.
    size: 16
    # Controls the timeout for a batch. If a batch is incomplete and a new block has not been received within
    # `timeout` milliseconds, the batch will be emitted, despite the fact it has less the `size` blocks.
    # timeout-ms: 10000
