event-stream:
  batch:
    size: 16
    timeoutMillis: 30000
  websocket:
    uri: ws://localhost:26657
  uri: http://localhost:26657
  rpc:
    uri: http://localhost:26657
  height:
    from: 1
  skipEmptyBlocks: false
node: http://localhost:26657
from: 6278600